# Generated by Django 4.2.28 on 2026-02-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tiktok_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(default='Afrobeats', max_length=100)),
                ('is_unsigned', models.BooleanField(default=True)),
                ('location', models.CharField(default='Nigeria', max_length=100)),
                ('current_subs', models.IntegerField(default=0)),
                ('prev_subs', models.IntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
