# Generated by Django 4.2.28 on 2026-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_artist_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='current_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='prev_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='prev_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
