# Generated by Django 4.2.28 on 2026-03-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_artist_current_comments_artist_prev_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Hide non-music/spam channels from the frontend'),
        ),
    ]
