# Generated by Django 4.2.28 on 2026-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_artist_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='discovered_on',
            field=models.CharField(default='youtube', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='prev_tiktok_follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='prev_tiktok_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok_follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok_likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
